### ISSUE TITLE
log4net 3.0.0 logfile issue

### ISSUE THREAD

**Issue by lanesCSO** [apache/logging-log4net#188] opened 2024-09-26 08:57 UTC
Using .net8 and upgrading from 2.0.17 and this config no longer works

```
<log4net>
  <root>
    <level value="ALL" />
    <appender-ref ref="FileAppender" />
  </root>
  <appender name="FileAppender" type="log4net.Appender.FileAppender">
    <threshold value="ALL" />
    <file type="log4net.Util.PatternString" value="Logs\Log4Net.[%processid].log" />
    <appendToFile value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date [%property{MachineName}] [%property{correlationID}] [%thread] %level %class.%method:%line - %message%newline" />
    </layout>
  </appender>
</log4net>
```

If I remove `type="log4net.Util.PatternString"` then the logfile is created but there is no pattern transformed to processid. 

Any help much appreciated

**Comment by FreeAndNil** [comment] 2024-09-26 09:47
Hi @lanesCSO,
this bug was fixed in https://www.nuget.org/packages/log4net/3.0.1-preview.2
We will release the final 3.0.1 at the end of this week.

Duplicate of #183 
Related to #184, #185, #186, #187

**Closed by FreeAndNil** 2024-09-26 09:47 UTC
